import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1779530475956 implements MigrationInterface {
    name = 'InitialSchema1779530475956'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."reviews_status_enum" AS ENUM('pending', 'approved', 'rejected', 'flagged')`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "product_id" character varying(26) NOT NULL, "user_id" character varying(26) NOT NULL, "order_id" character varying(20) NOT NULL, "rating" smallint NOT NULL, "title" character varying(120), "comment" text, "images" jsonb DEFAULT '[]', "is_verified_purchase" boolean NOT NULL DEFAULT true, "helpful_count" integer NOT NULL DEFAULT '0', "flag_count" integer NOT NULL DEFAULT '0', "status" "public"."reviews_status_enum" NOT NULL DEFAULT 'approved', "merchant_reply" text, "merchant_replied_at" TIMESTAMP, "merchant_id" character varying(26), CONSTRAINT "CHK_2ea381a5c2f8bef0073a48f6bd" CHECK ("rating" BETWEEN 1 AND 5), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7b06c23cf52ca8aea0dcaf0ee2" ON "reviews" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4b0ed40bdd0f318108612c285" ON "reviews" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_728447781a30bc3fcfe5c2f1cd" ON "reviews" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9482e9567d8dcc2bc615981ef4" ON "reviews" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "review_helpful" ("id" character varying(26) NOT NULL, "review_id" character varying(26) NOT NULL, "user_id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_357fdd46b34876b94a72cb566f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_636e9a5efc3e4f3126a72f20c5" ON "review_helpful" ("review_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."coupons_type_enum" AS ENUM('percentage', 'flat', 'free_shipping')`);
        await queryRunner.query(`CREATE TYPE "public"."coupons_scope_enum" AS ENUM('all', 'category', 'merchant', 'product', 'first_order')`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "code" character varying(30) NOT NULL, "description" text, "type" "public"."coupons_type_enum" NOT NULL, "value" numeric(10,2) NOT NULL, "max_discount" numeric(10,2), "min_order_value" numeric(10,2), "scope" "public"."coupons_scope_enum" NOT NULL DEFAULT 'all', "scope_id" character varying(26), "max_uses" integer, "used_count" integer NOT NULL DEFAULT '0', "max_uses_per_user" integer, "is_active" boolean NOT NULL DEFAULT true, "starts_at" TIMESTAMP, "expires_at" TIMESTAMP, "created_by" character varying(26), CONSTRAINT "UQ_e025109230e82925843f2a14c48" UNIQUE ("code"), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_98407590d8ff162266a7dc5704" ON "coupons" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_421cb28b5553d66d1eff63f76f" ON "coupons" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e025109230e82925843f2a14c4" ON "coupons" ("code") `);
        await queryRunner.query(`CREATE TABLE "coupon_usages" ("id" character varying(26) NOT NULL, "coupon_id" character varying(26) NOT NULL, "user_id" character varying(26) NOT NULL, "order_id" character varying(20) NOT NULL, "discount_applied" numeric(10,2) NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_01ff9a1cac559c4ae2e4179d0a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f017af60a02209a6b045f673ca" ON "coupon_usages" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1fa2cbd0178e94678cd55e376b" ON "coupon_usages" ("coupon_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('active', 'inactive', 'out_of_stock', 'pending_review', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "merchant_id" character varying(26) NOT NULL, "category_id" character varying(26) NOT NULL, "name" character varying(200) NOT NULL, "slug" character varying(220) NOT NULL, "description" text NOT NULL, "price" numeric(10,2) NOT NULL, "compare_price" numeric(10,2), "stock" integer NOT NULL DEFAULT '0', "sku" character varying(100), "low_stock_at" integer NOT NULL DEFAULT '10', "status" "public"."products_status_enum" NOT NULL DEFAULT 'active', "images" jsonb NOT NULL DEFAULT '[]', "variants" jsonb DEFAULT '[]', "avg_rating" numeric(3,1) NOT NULL DEFAULT '0', "review_count" integer NOT NULL DEFAULT '0', "total_sold" integer NOT NULL DEFAULT '0', "is_featured" boolean NOT NULL DEFAULT false, "flag_count" integer NOT NULL DEFAULT '0', "metadata" jsonb, CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327" UNIQUE ("sku"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7d80d63e220c4511ab4b659584" ON "products" ("merchant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1846199852a695713b1f8f5e9a" ON "products" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_464f927ae360106b783ed0b410" ON "products" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."merchants_status_enum" AS ENUM('pending', 'approved', 'suspended', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "merchants" ("id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "user_id" character varying(26) NOT NULL, "store_name" character varying(120) NOT NULL, "store_slug" character varying(130) NOT NULL, "description" text, "logo_url" character varying(500), "banner_url" character varying(500), "status" "public"."merchants_status_enum" NOT NULL DEFAULT 'pending', "is_verified" boolean NOT NULL DEFAULT false, "is_online" boolean NOT NULL DEFAULT true, "commission_rate" numeric(5,2) NOT NULL DEFAULT '8', "total_revenue" numeric(10,2) NOT NULL DEFAULT '0', "available_balance" numeric(10,2) NOT NULL DEFAULT '0', "stripe_account_id" character varying, "avg_rating" numeric(3,1) NOT NULL DEFAULT '0', "return_policy_days" integer NOT NULL DEFAULT '0', "business_info" jsonb, CONSTRAINT "UQ_698f612a3134c503f711479a4e5" UNIQUE ("user_id"), CONSTRAINT "UQ_93c833424f1bf8d19f3d3b25e12" UNIQUE ("store_slug"), CONSTRAINT "REL_698f612a3134c503f711479a4e" UNIQUE ("user_id"), CONSTRAINT "PK_4fd312ef25f8e05ad47bfe7ed25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."addresses_type_enum" AS ENUM('home', 'work', 'other')`);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "user_id" character varying(26) NOT NULL, "type" "public"."addresses_type_enum" NOT NULL DEFAULT 'home', "full_name" character varying(160) NOT NULL, "email" character varying(160), "phone" character varying(20) NOT NULL, "address_line1" character varying(300) NOT NULL, "address_line2" character varying(200), "city" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "zip_code" character varying(20) NOT NULL, "country" character varying(80) NOT NULL DEFAULT 'United States', "is_default" boolean NOT NULL DEFAULT false, "lat" numeric(9,6), "lng" numeric(9,6), CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "name" character varying(80) NOT NULL, "slug" character varying(90) NOT NULL, "icon_url" character varying(500), "parent_id" character varying(26), "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wishlist" ("id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "user_id" character varying(26) NOT NULL, "product_id" character varying(26) NOT NULL, CONSTRAINT "PK_620bff4a240d66c357b5d820eaa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c00c97c645a6be88349354e8f3" ON "wishlist" ("user_id", "product_id") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending_payment', 'confirmed', 'processing', 'ready_for_pickup', 'picked_up', 'in_transit', 'delivered', 'cancelled', 'return_requested', 'returned', 'refunded', 'disputed')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_shipping_method_enum" AS ENUM('free', 'express', 'next_day')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" character varying(20) NOT NULL, "customer_id" character varying(26) NOT NULL, "driver_id" character varying(26), "address_id" character varying(26) NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending_payment', "shipping_method" "public"."orders_shipping_method_enum" NOT NULL DEFAULT 'free', "subtotal" numeric(10,2) NOT NULL, "shipping_fee" numeric(10,2) NOT NULL DEFAULT '0', "discount" numeric(10,2) NOT NULL DEFAULT '0', "total" numeric(10,2) NOT NULL, "coupon_code" character varying(30), "stripe_payment_intent_id" character varying, "delivery_otp" character varying, "status_history" jsonb NOT NULL DEFAULT '[]', "estimated_delivery" TIMESTAMP, "delivered_at" TIMESTAMP, "cancelled_at" TIMESTAMP, "cancel_reason" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c884e321f927d5b86aac7c8f9e" ON "orders" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_222cd7bf166a2d7a6aad9cdebe" ON "orders" ("driver_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_772d0ce0473ac2ccfa26060dbe" ON "orders" ("customer_id") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" character varying(26) NOT NULL, "order_id" character varying(20) NOT NULL, "product_id" character varying(26) NOT NULL, "merchant_id" character varying(26) NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(10,2) NOT NULL, "total_price" numeric(10,2) NOT NULL, "variant_id" character varying, "variant_snapshot" jsonb, "product_name" character varying NOT NULL, "product_image" character varying, "commission" numeric(10,2) NOT NULL DEFAULT '0', "merchant_earnings" numeric(10,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('customer', 'merchant', 'delivery_partner', 'sub_admin', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_provider_enum" AS ENUM('local', 'google', 'facebook')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "first_name" character varying(80) NOT NULL, "last_name" character varying(80) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20), "password_hash" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'customer', "provider" "public"."users_provider_enum" NOT NULL DEFAULT 'local', "provider_id" character varying, "is_verified" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "avatar_url" character varying(500), "customer_settings" jsonb, "refresh_token_hash" character varying, "last_login_at" TIMESTAMP, "fcm_token" character varying, "is_suspended" boolean NOT NULL DEFAULT false, "suspension_reason" character varying, "warning_count" integer NOT NULL DEFAULT '0', "moderation_notes" text, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0408cb491623b121499d4fa238" ON "users" ("last_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef2fb839248017665e5033e730" ON "users" ("first_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_875541f7dbe1b8565414f9f80b" ON "users" ("phone") WHERE "phone" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "platform_settings" ("id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "key" character varying(100) NOT NULL, "value" jsonb NOT NULL DEFAULT '{}', "updated_by" character varying(26), CONSTRAINT "UQ_5d9031e30fac3ec3ec8b9602e17" UNIQUE ("key"), CONSTRAINT "PK_2934aeb70ec285196dcab4a2e96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5d9031e30fac3ec3ec8b9602e1" ON "platform_settings" ("key") `);
        await queryRunner.query(`CREATE TYPE "public"."support_tickets_category_enum" AS ENUM('order', 'payment', 'delivery', 'account', 'merchant', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."support_tickets_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."support_tickets_status_enum" AS ENUM('open', 'in_progress', 'resolved', 'closed')`);
        await queryRunner.query(`CREATE TABLE "support_tickets" ("id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "ticket_no" character varying(24) NOT NULL, "customer_id" character varying(26) NOT NULL, "assigned_to_id" character varying(26), "order_id" character varying(20), "subject" character varying(180) NOT NULL, "description" text NOT NULL, "category" "public"."support_tickets_category_enum" NOT NULL DEFAULT 'other', "priority" "public"."support_tickets_priority_enum" NOT NULL DEFAULT 'medium', "status" "public"."support_tickets_status_enum" NOT NULL DEFAULT 'open', "metadata" jsonb, "resolved_at" TIMESTAMP WITH TIME ZONE, "closed_at" TIMESTAMP WITH TIME ZONE, "last_reply_at" TIMESTAMP WITH TIME ZONE, "last_reply_by_id" character varying(26), CONSTRAINT "UQ_fcb4080d9d57424031c4880cb21" UNIQUE ("ticket_no"), CONSTRAINT "PK_942e8d8f5df86100471d2324643" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82013b41f4246f8f0c432bf55a" ON "support_tickets" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_d9de5400cea009d93a7a436ade" ON "support_tickets" ("assigned_to_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcccb94a1fe4c82aefeab8c23a" ON "support_tickets" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cae81694804986ef32be155d34" ON "support_tickets" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba7b1a2ed4051fb3b39ff95444" ON "support_tickets" ("status") `);
        await queryRunner.query(`CREATE TABLE "support_ticket_replies" ("id" character varying(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "ticket_id" character varying(26) NOT NULL, "author_id" character varying(26) NOT NULL, "message" text NOT NULL, "is_internal" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_21cbd63caf2e238c44493cf7350" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fd56b388a5b397cf82dcb4ea64" ON "support_ticket_replies" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4bce27e93c5931d67621035078" ON "support_ticket_replies" ("author_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_60d0d175c552e94b25d954f079" ON "support_ticket_replies" ("ticket_id") `);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_9482e9567d8dcc2bc615981ef44" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_7d80d63e220c4511ab4b6595846" FOREIGN KEY ("merchant_id") REFERENCES "merchants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD CONSTRAINT "FK_698f612a3134c503f711479a4e5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD CONSTRAINT "FK_512bf776587ad5fc4f804277d76" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD CONSTRAINT "FK_16f64e06715ce4fea8257cc42c5" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_222cd7bf166a2d7a6aad9cdebee" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_d39c53244703b8534307adcd073" FOREIGN KEY ("address_id") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_tickets" ADD CONSTRAINT "FK_bcccb94a1fe4c82aefeab8c23ad" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_tickets" ADD CONSTRAINT "FK_d9de5400cea009d93a7a436adec" FOREIGN KEY ("assigned_to_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_ticket_replies" ADD CONSTRAINT "FK_60d0d175c552e94b25d954f0797" FOREIGN KEY ("ticket_id") REFERENCES "support_tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_ticket_replies" ADD CONSTRAINT "FK_4bce27e93c5931d676210350788" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "support_ticket_replies" DROP CONSTRAINT "FK_4bce27e93c5931d676210350788"`);
        await queryRunner.query(`ALTER TABLE "support_ticket_replies" DROP CONSTRAINT "FK_60d0d175c552e94b25d954f0797"`);
        await queryRunner.query(`ALTER TABLE "support_tickets" DROP CONSTRAINT "FK_d9de5400cea009d93a7a436adec"`);
        await queryRunner.query(`ALTER TABLE "support_tickets" DROP CONSTRAINT "FK_bcccb94a1fe4c82aefeab8c23ad"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_d39c53244703b8534307adcd073"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_222cd7bf166a2d7a6aad9cdebee"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP CONSTRAINT "FK_16f64e06715ce4fea8257cc42c5"`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP CONSTRAINT "FK_512bf776587ad5fc4f804277d76"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP CONSTRAINT "FK_698f612a3134c503f711479a4e5"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_7d80d63e220c4511ab4b6595846"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_9482e9567d8dcc2bc615981ef44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60d0d175c552e94b25d954f079"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bce27e93c5931d67621035078"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd56b388a5b397cf82dcb4ea64"`);
        await queryRunner.query(`DROP TABLE "support_ticket_replies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba7b1a2ed4051fb3b39ff95444"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cae81694804986ef32be155d34"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcccb94a1fe4c82aefeab8c23a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9de5400cea009d93a7a436ade"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82013b41f4246f8f0c432bf55a"`);
        await queryRunner.query(`DROP TABLE "support_tickets"`);
        await queryRunner.query(`DROP TYPE "public"."support_tickets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."support_tickets_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."support_tickets_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d9031e30fac3ec3ec8b9602e1"`);
        await queryRunner.query(`DROP TABLE "platform_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_875541f7dbe1b8565414f9f80b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef2fb839248017665e5033e730"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0408cb491623b121499d4fa238"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_provider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_772d0ce0473ac2ccfa26060dbe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_222cd7bf166a2d7a6aad9cdebe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c884e321f927d5b86aac7c8f9e"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_shipping_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c00c97c645a6be88349354e8f3"`);
        await queryRunner.query(`DROP TABLE "wishlist"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP TYPE "public"."addresses_type_enum"`);
        await queryRunner.query(`DROP TABLE "merchants"`);
        await queryRunner.query(`DROP TYPE "public"."merchants_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_464f927ae360106b783ed0b410"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1846199852a695713b1f8f5e9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d80d63e220c4511ab4b659584"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fa2cbd0178e94678cd55e376b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f017af60a02209a6b045f673ca"`);
        await queryRunner.query(`DROP TABLE "coupon_usages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e025109230e82925843f2a14c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_421cb28b5553d66d1eff63f76f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98407590d8ff162266a7dc5704"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_scope_enum"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_636e9a5efc3e4f3126a72f20c5"`);
        await queryRunner.query(`DROP TABLE "review_helpful"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9482e9567d8dcc2bc615981ef4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_728447781a30bc3fcfe5c2f1cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4b0ed40bdd0f318108612c285"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b06c23cf52ca8aea0dcaf0ee2"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TYPE "public"."reviews_status_enum"`);
    }

}
